### ISSUE TITLE
Remove some training modules

### ISSUE THREAD

**Issue by MaybeJustJames** [vibbits/gentle-hands-on-python#15]
* Plotting (depending on outcome of survey)
* Modules (instead talk about importing standard library modules)
* Sets
* complex
* Remove `tuple` if there's time left

**Comment by tmuylder** [comment]
Modules done
Sets done

**Comment by tmuylder** [comment]
- [] Plotting (depending on outcome of survey)
- [x] Modules (instead talk about importing standard library modules)
- [x] Sets
- [] complex
- [] Remove tuple if there's time left

**Comment by tmuylder** [comment]
Changes in branch *remove-stuff-issue15*

- [ ] Plotting (depending on outcome of survey)
- [x] Modules (instead talk about importing standard library modules)
- [x] Sets
- [x] complex
- [ ] Remove tuple if there's time left

**Comment by tmuylder** [comment]
Merged Modules, Sets, Complex stuff. Not plotting and didn't remove tuples

**Comment by tmuylder** [comment]
Plotting is still part of the course (now three days)
Tuples will also remain present for now (as we have three days)
