### ISSUE TITLE
Reorganise chapters

### ISSUE THREAD

**Issue by tmuylder** [vibbits/gentle-hands-on-python#39]
## Day 1
1. Introduction
> Introduce projects
2. Basics
3. Functions
4. Conditions

> Work on project

## Day 2
5. Lists & tuples
6. Looping
> Work on project

## Day 3
7. Dictionaries
8. I/O
> Work on project
9. Modules
> Review project

**Comment by tmuylder** [comment]
Final project:
1. Read in a file containing reads
2. Assemble the sequence
3. Compare the assembled sequence to the real sequence

After chapter 4: start project
1. Write a function to compute edit distance
2. Write a function to join end-to-end, 2 reads

After chapter 7:
1. complete the edit distance function
2. Write function to generate alignment based on edit distance
3. Write a function to merge 2 fragments

After chapter 9: write a function to read in the read data and write out the assembled sequence
After chapt 10: make it all into a module
After chapter 11: make a plot

**Comment by MaybeJustJames** [comment]
Project links:
* https://en.wikipedia.org/wiki/Sequence_assembly#Greedy_algorithm
* https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000139618;r=13:32315086-32400268
* https://en.wikipedia.org/wiki/Sequence_alignment#Dynamic_programming
* https://en.wikipedia.org/wiki/Backtracking
* https://youtu.be/We3YDTzNXEk
* https://www.python-course.eu/levenshtein_distance.php
* https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Python
* https://www.cis.upenn.edu/~cis110/12su/hw/hw06/dynprog.shtml
* https://youtu.be/KASvlXYPCBI, https://youtu.be/sseqEefj6Gs, https://youtu.be/KO2UaG8eKEw
* https://data-science-sequencing.github.io/Win2018/lectures/lecture6/

**Comment by MaybeJustJames** [comment]
I propose removing the String formatting chapter. It's long and serves little purpose.

**Comment by MaybeJustJames** [comment]
This will require some re-organisation sure. And re-thinking how the projects are structured. But the projects were rushed. They deserve more thought.

**Comment by tmuylder** [comment]
I agree, I'm just hesitant for moving lists & tuples to W2 as it gives very little stuff to work with after W1...

**Comment by MaybeJustJames** [comment]
> I agree, I'm just hesitant for moving lists & tuples to W2 as it gives very little stuff to work with after W1...

Indeed. But "very little" is not "nothing". And for a beginner programmer it's actually a lot to take in and practice with. The sequence assembly project is set up for this (but can still be improved). I think we can adjust the "mutation finder" project too.

**Comment by MaybeJustJames** [comment]
Chapters have been reorganised
